name: ghenv
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvcc=11.8.89
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - cudatoolkit=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gtest=1.14.0
  - idna=3.4
  - importlib-metadata=7.2.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.8.19
  - python_abi=3.8
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.12
  - torchaudio=2.3.0
  - torchtriton=2.3.0
  - torchvision=0.18.0
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - werkzeug=3.0.3
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cftime==1.6.3
      - contourpy==1.1.1
      - cycler==0.12.1
      - einops==0.8.0
      - fonttools==4.51.0
      - fsspec==2024.3.1
      - huggingface-hub==0.22.2
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - matplotlib==3.7.5
      - netcdf4==1.6.5
      - packaging==24.0
      - protobuf==5.26.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - safetensors==0.4.3
      - scipy==1.10.1
      - tensorboardx==2.6.2.2
      - timm==0.9.16
      - tqdm==4.66.2
      - zipp==3.18.1

